<a href="https://colab.research.google.com/github/wuxquan/hello-world/blob/master/Qthe_first_one_saved_once_in_github.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

not sure numpy in env. or not, so import, don't know where to check env.


In [2]:
import numpy as np
print(np.__version__)



1.18.5


In [6]:
a=[10,20,30,40,50]
print(a)
type(a)
b=np.array(a)
print(b)
type(b)

[10, 20, 30, 40, 50]
[10 20 30 40 50]


numpy.ndarray

In [8]:
b+100

array([110, 120, 130, 140, 150])

In [20]:
c=b+1.1
print(c)
print(c.dtype)
print(b.dtype)
b.shape

[11.1 21.1 31.1 41.1 51.1]
float64
int64


(5,)

In [22]:
a =np.array([1,2,3,4,5,6,7,8,9,10], ndmin=2) #set this as two dims
print(a)
a.shape

[[ 1  2  3  4  5  6  7  8  9 10]]


(1, 10)

In [25]:
a =np.array([1,2,3,4,5,6,7,8,9,10], dtype=complex)
print(a)
print(a.shape)
a.dtype

[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j  9.+0.j
 10.+0.j]
(10,)


dtype('complex128')

In [34]:
a = np.array([1,2,3]) #single dim
print(a.shape)
b = np.array([[1,2,3], [4,5,6]]) #two dims
print(b)
b.shape


(3,)
[[1 2 3]
 [4 5 6]]


(2, 3)

In [39]:
c = np.array([[[1,2,3], [4,5,6]],[[11,22,33],[44,55,66]]])
print(c)
c.shape


[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


(2, 2, 3)

In [41]:
c = np.array([[1,2,3], [4,5,6],[11,22,33],[44,55,66]]) # two dims
print(c)
c.shape

[[ 1  2  3]
 [ 4  5  6]
 [11 22 33]
 [44 55 66]]


(4, 3)